### PR TITLE
New handling for getMetadataForTrack

### PR DESCRIPTION
**Pull request by saivert**
This changes it so that if no track is currently playing it will return the metadata for the currently selected track in the current playlist.
It also uses the correct deadbeef API to get currently playing playlist if a track is playing.

I'm also having some further ideas for how to improve this code as `DB_EV_TRACKINFOCHANGED` gives you a struct `ddb_event_track_t` that contains a `DB_playItem_t *track` member.
I just want you to look at what I came up with now and if this is an acceptable approach.

### CODE REVIEW

**Comment by Serranya** [comment]
The commit itself is looking good to me.

But I don't quite understand why you want to emit new Metadata just because someone changed the selection while nothing is playing.

I will probably merge this anyway but I am interested in your reasoning.

**Comment by saivert** [comment]
Some mpris clients show track information even if player isn't currently playing. Gnome's own mpris client does this. It is clear which track you will be playing when you click play.
Alternative would be to just return no track and have it show "Unknown track". This is what I noticed when testing against GNOME's own mpris client.

**Comment by JasonLG1979** [comment]
I just happened to be checking out MPRIS server implementations and I came across this PR. I may be able to offer some insight as far as what you could/should do to indicate that there is no track playing. By spec you should emit a metadata change with metadata that only contains a mpris:trackid of /org/mpris/MediaPlayer2/TrackList/NoTrack . To make GNOME Shell's default MPRIS client not show your player you should emit a CanPlay false prop change. With https://extensions.gnome.org/extension/55/media-player-indicator/ emitting a PlaybackStatus of Stopped will hide the song info.

So if you did all 3 of those things when there was no song you'd be pretty safe I think. I don't think cycling though metadata as songs are selected is a good idea.

* Disclaimer * I wrote a good part of the Pithos MPRIS plugin and am the current lead dev of the media-player-indicator.

**Comment by saivert** [comment]
Good point. Some players like quod libet and Lollypop doesn't even let you stop playback (stop = pause) so they always show some metadata regardless.
I will revise this PR.

**Comment by JasonLG1979** [comment]
> Some players like quod libet and Lollypop doesn't even let you stop playback

Very true. Many MPRIS clients don't even have stop buttons. We have a stop button in media-player-indicator because some players still use stop, but I'm actively trying to find out which players don't allow stop so I can hide the button if I can. It's a shame there isn't a CanStop prop in the spec,lol!!!

**Comment by saivert** [comment]
This mpris2 server currently returns TRUE always on CanPlay, CanPause. So GNOME's built-in client shows Unknown Track in stopped state. Wonder if this is a bug in that client implementation because it should really show Not currently playing. If it was tested against GNOME music and many other contemporary players which don't support the notion of Stop then it makes sense.

**Comment by JasonLG1979** [comment]
> This mpris2 server currently returns TRUE always on CanPlay, CanPause. So GNOME's built-in client shows Unknown Track in stopped state. Wonder if this is a bug in that client implementation because it should really show Not currently playing. If it was tested against GNOME music and many other contemporary players which don't support the notion of Stop then it makes sense.

The MPRIS spec is often misunderstood. There's a lot of copypasta. Not very many people actually take the time to read and understand it. For whatever reason they have decided to use CanPlay to decide if or not to show a player. It's not what I've done but good luck trying to convince the GNOME dev's they're wrong.lol!!!

**Pull request merged**
